#include <CakeEngine/graphics/opengl/opengl.hpp>


const CKType CK_TYPE_BYTE = {GL_BYTE, 1};
const CKType CK_TYPE_UNSIGNEDBYTE = {GL_UNSIGNED_BYTE, 1};
const CKType CK_TYPE_SHORT = {GL_SHORT, 2};
const CKType CK_TYPE_UNSIGNEDSHORT = {GL_UNSIGNED_SHORT, 2};
const CKType CK_TYPE_INT = {GL_INT, 4};
const CKType CK_TYPE_UNSIGNEDINT = {GL_UNSIGNED_INT, 4};
const CKType CK_TYPE_FLOAT = {GL_FLOAT, 4};
const CKType CK_TYPE_2BYTES = {GL_2_BYTES, 2};
const CKType CK_TYPE_3BYTES = {GL_3_BYTES, 3};
const CKType CK_TYPE_4BYTES = {GL_4_BYTES, 4};
const CKType CK_TYPE_DOUBLE = {GL_DOUBLE, 8};
const CKType CK_TYPE_UNSIGNEDINT_24_8 = {GL_UNSIGNED_INT_24_8, 4};


const CKPixelFormat CK_PIXELFORMAT_RGB888 = CKPixelFormat{SDL_AllocFormat(SDL_PIXELFORMAT_RGB888), GL_RGB8, GL_RGB, GL_RGB};
const CKPixelFormat CK_PIXELFORMAT_RGBA8888 = CKPixelFormat{SDL_AllocFormat(SDL_PIXELFORMAT_RGBA8888), GL_RGBA8, GL_RGBA, GL_RGBA};


CKFramebufferMode CK_FRAMEBUFFERMODE_COLOR = {GL_RGBA, GL_RGBA, GL_COLOR_ATTACHMENT0, GL_UNSIGNED_BYTE};
CKFramebufferMode CK_FRAMEBUFFERMODE_DEPTH = {GL_DEPTH_COMPONENT24, GL_DEPTH_COMPONENT, GL_DEPTH_ATTACHMENT, GL_FLOAT};
CKFramebufferMode CK_FRAMEBUFFERMODE_STENCIL = {GL_DEPTH24_STENCIL8, GL_DEPTH_STENCIL, GL_DEPTH_STENCIL_ATTACHMENT, GL_UNSIGNED_INT_24_8};

